objects_xml_file: /home/dsbrown/Code/AustinVillaatHome/GPSRCmdGen/CommonFiles/Objects.xml
locations_xml_file: /home/dsbrown/Code/AustinVillaatHome/GPSRCmdGen/CommonFiles/Locations.xml
names_xml_file: /home/dsbrown/Code/AustinVillaatHome/GPSRCmdGen/CommonFiles/Names.xml
grammar_location: /home/dsbrown/Code/AustinVillaatHome/GPSRCmdGen/GPSRCmdGen/Resources/
grammar_files: [Category1Grammar.txt, CommonRules.txt]    
semantics_file: ./semantics.csv
artificial_terminals: [$whattosay]
